# Source: https://github.com/igrr/esp32-cam-demo/blob/master/.travis.yml
sudo: false
language: bash
os:
  - linux
dist: xenial

addons:
  apt:
    packages:
      - gperf
      - python
      - python-serial

before_install:
  # Save path to the git respository
  - PROJECT_PATH=$(pwd)

install:
  # Install ESP32 toochain following steps as desribed
  # in http://esp-idf.readthedocs.io/en/latest/linux-setup.html
  #
  # Get required packages - already done above, see addons: apt: packages:
  # - sudo apt-get install git wget make libncurses-dev flex bison gperf python python-serial
  # Prepare directory for the toolchain
  - mkdir -p ~/esp
  - cd ~/esp
  # Download binary toolchain for the ESP32
  - wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
  - tar -xzf xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
  # Make xtensa-esp32-elf available for all terminal sessions
  - export PATH=$PATH:$HOME/esp/xtensa-esp32-elf/bin
  # Get ESP-IDF from github
  - git clone --recursive https://github.com/espressif/esp-idf.git
  # Set the path to ESP-IDF directory
  - export IDF_PATH=~/esp/esp-idf

script:
  # Install Python dependencies.
  - python -m pip install --user -r /home/travis/esp/esp-idf/requirements.txt
  # Go back to the git repository
  - cd $PROJECT_PATH
  # Update configuration so that kconfig doesn't start interactive mode
  - make defconfig
  # Build project from the git repository
  - make

deplay:
  provider: releases
  api_key:
    secure: dERqAQfF8UAotq+GCz5OWhQP805oY2GBYdsJ+Xu3U/yflfjdTN/KGQ0zLFMpVxwL3ff4UD+WT76iZH5DFcMPXWftBFqe9K3FC6M2JCCSI5/T4gQuvfA9hAha+OM4Od26OMyN8lduW8lZWhZzLlGZkhV/5dLdagObi1mZ0cUkMaEAxn+/HgVk2R9UTSn1gWLhKjXTTKH215aMmUI1w0BjfcOEzOJOC1293LVmYOj8Vr9IiDX/SiPbBVaEd4+UQZ/VQ0/ako+aB9yBAGdLFn/deaTLcWcscQWlQpIrWla6IWVu93Uue8rcNs4Kffcm8rF6qC2udURXGS1VivkYYE9zEdLikG9pOvDAw7vEp/LuCIKgh7Dk8iLk4UJPyu3WN0eKhVvyo5M8Oa7ItgJPPuPhuF6fxZoM8diIGvDJYnyiFjO8G3VpH/b1L1usA8ZXotXorWUepsk/ozFDKPdTr9rtJLOxuBCX8yhpxeVxUXvq8j0OEMHuE6IB8cCvD9he51xN5T3iuDyKK+z31NbGRU56yhUTb7YQ3bmaBgHZpM7dpXwnUea9R3ddNwWryL5zfo29I48NRhzEHT2vkhXSYZOYQyQemjZetFjLf9p93H0tqq62mBLBQQP38mvluoZWpN6or+nRQDt2J9amtwsHTKCwMxq6t0cwgwWkTwETK0PPUDE=
  skip_cleanup: true
  on:
    tags: true
    branch: master
  draft: true
  file:
    - build/ota_data_initial.bin
    - build/bootloader/bootloader.bin
    - build/diodehub-esp.bin
    - build/default.bin
